# Step 1
import pickle

ClassAllPlayersData_dictionary = {'remote_hostname': 'google.com', 'remote_port': 80}

'''we use the with keyword and the open function to create a file handle 
that points to config.dictionary in the same directory where we will run 
save_dictionary_to_file.py.

The first string that we supply to the open function denotes the 
filepath to write our dictionary of values. The second string that we 
supply to the open function indicates that we want a file handle that 
writes binary contents to the file.

The with keyword ensures that the file handle generated by the open 
function is closed after our dictionary is serialized to file
'''  
 
# Step 2
with open('ClassAllPlayersData.dictionary', 'wb') as ClassAllPlayersData_dictionary_file:
 
      # Step 3

      '''
      we use the pickle.dump function to write the contents of our dictionary 
      to a file that will be named as config.dictionary.

      After running save_dictionary_to_file.py, we should be able to see the 
      config.dictionary file in the same directory where we run our Python script.
      '''

      pickle.dump(ClassAllPlayersData_dictionary, ClassAllPlayersData_dictionary_file)


